[package]
name = "buf"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Read buffer"
license = "MIT OR Apache-2.0"
repository = "https://github.com/strake/buf.rs"

[dependencies]
containers = "0.8"
i-o = "0.4"
loca = "0.6"
